### ISSUE TITLE
Server crash on first run -  java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by cauliflower69** [Ipsis/BuildersGuides#10]
http://pastebin.com/bFZp54Bj

**Comment by Ipsis** [comment]
Apologies, I've only just seen this report. I'll set up a server/client instance and try to reproduce this, as I've made a couple of dedicated server mistakes in the past.

**Comment by Ipsis** [comment]
That was simple to reproduce! I'll get that fixed up and push a new release as soon as I understand what has changed.

**Comment by Ipsis** [comment]
I've tested 1.8.9 as well, but this only seems to be an issue on 1.9.
The packet handler is crashing for the message being sent to the client. The packet handler has client code in it, however that handler is also being registered (correctly) on the server.

So I need to provide a dummy handler for the server to use.
https://github.com/TheGreyGhost/MinecraftByExample/blob/master/src/main/java/minecraftbyexample/mbe60_network_messages/StartupCommon.java

**Comment by Ipsis** [comment]
1a6ef81b450b81975c672abd02742b391db7b404

**Comment by cauliflower69** [comment]
Thanks
