### ISSUE TITLE
Marker cards display in every creative tab

### ISSUE THREAD

**Issue by cabbby** [Ipsis/BuildersGuides#20]
In creative tabs, marker cards seem to appear everywhere... does it mean to do that?

Minecraft version: 1.12.2

**Comment by Ipsis** [comment]
Apologies, I've only just checked this repository.
No it shouldn't appear everywhere in the creative tabs.
I'll look into that and see how to limit it to the correct tab

**Comment by cabbby** [comment]
thx for your work :)
