### ISSUE TITLE
Show block count (distance, inclusive) in Ghost Block mode

### ISSUE THREAD

**Issue by acook** [Ipsis/BuildersGuides#21]
In Builder's Guides most modes (except Ghost) expect a bounding block at the far end. When we're planning out a new area we're not always sure where that end should be until we measure it and mock out the corners. The Ghost Block Mode is pretty close but doesn't show the numbers like the other modes do.

Right now my group uses the Bibliocraft Tape Measure for measuring out new constructions, but it doesn't show the distance in the world when you're using it, just in the chat after the second click. It's cool but I think Builder's Guides are overall better and it'd be really nice to have that feature built in.

Alternatively, a new "measurement" mode which shows the distance to the farthest ghost block and highlights the middle block(s). If it made a closed-box outline like the Ghost Block Cuboid mode that would be perfect. 

Either way, great mod and thanks for making it!

**Comment by Ipsis** [comment]
Didn't think anyone really used this mod - but glad to hear that they do!
I should have the information on the ghost blocks to display the distance, so I'll see if I can overlay that in a sensible way onto the screen.
When I've coded something up I'll include a screenshot here to see if I'm going in the right direction.

**Comment by Ipsis** [comment]
So I've had a look at this and it turns out that I don't have the data in the renderer to display the distances. So this will take a bit more effort than I first thought.
But I'll get there eventually!

**Comment by Ipsis** [comment]
![2018-07-22_10 59 36](https://user-images.githubusercontent.com/5602759/43044475-6c4be72c-8d9e-11e8-853f-a271b552fc62.png)

So I have the initial values over for display. It is a little busy looking when you are using more than one direction.  The other thing is that the value includes the guide values - so if you have 7 ghost blocks then it will display 8(?)

So is this what you are looking for, is the value displayed correct and is the display too busy?

**Comment by acook** [comment]
The number being inclusive seems fine to me. 

I see what you mean about it being busy but it's only 5 numbers. Without breaking from the way the numbers are rendered I see another option anyway. 

Brainstorming alternatives.... Rendering the number of the block on each block the font could be larger and more spread out?

**Comment by Ipsis** [comment]
I'll give the per-block version a try.
Never tried to render text on a specific face ... this could stretch my OpenGL knowledge a bit! :)

**Comment by Ipsis** [comment]
I have to apologise here and say that this isn't going to get done anytime soon - which you've probably guessed already. 
I'm struggling to get any enthusiasm for updating my mods just now (aside from critical bug fixes). 
I'm trying to get that enthusiasm back by writing a new version of my other mod Woot for 1.13.

I can hopefully come back and add this at a later date and if not then I'll certainly look at putting it in a 1.13 build. Again my apologies.

**Comment by acook** [comment]
Bummer, I was talking to a friend on our server about it and we were brainstorming ideas for it. Thanks for the time and effort you've put into it. 

Personally, I don't know how likely it will be that this server will ever make it to 1.13 due to major changes in Forge and base Minecraft which will likely break mods that we rely on. But here's hoping that everyone (or at least most) eventually will!

**Comment by acook** [comment]
Closing this due to this probably not ever being anyone's priority.
I hope everything is going well for you!
