### ISSUE TITLE
Crash related to builder's guides

### ISSUE THREAD

**Issue by acook** [Ipsis/BuildersGuides#22]
Today was the first time I've encountered a crash with Builder's guides, so I can't claim it wasn't a fluke, but I wanted to log it here just in case.

I was walking over to a hole I'd dug that had an Immersive Engineering floodlight next to it. I had one of the Builder's Guides blocks in my hand and was about to place it above the floodlight to plan out the utility building when the screen went white and a few seconds later VanillaFix popped up its friendly error message saying that Minecraft had crashed and provided me with the following information: 

https://paste.dimdev.org/lirifucove.mccrash

**Comment by Ipsis** [comment]
I've seen a very similar crash a long time ago in the 1.10 version of the mod so it could well be a slight twist on that. [https://github.com/Ipsis/BuildersGuides/issues/13]

I'll have to install Immersive Engineering and see if it is a corner case that I'm not handling.

Update: So after looking at the code it may well be the same bug. I think I forget to port the fix from 1.10 to 1.12 - <innocent whistling>

Once I've tidied up the Woot crash problems, I'll get this and #21 looked at :)

**Comment by Ipsis** [comment]
So I've had a look at this and it turns out that I don't have the data in the renderer to display the distances. So this will take a bit more effort than I first thought.
But I'll get there eventually!

**Comment by Ipsis** [comment]
I've been unable to get this to crash with a floodlight.
However the renderer code could do with a bit of a cleanup, so hopefully I'll spot something silly when I do that,.

**Comment by acook** [comment]
Closing this one as well!
